# Install the VS Code "REST Client" to make the most of this file:
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### shoe-catalog-api
@testEndpoint = http://localhost:3000

### Root
GET {{testEndpoint}}
### 
GET {{testEndpoint}}/not-there

### Shoes
### List all shoes
GET {{testEndpoint}}/shoes
### Get the shoe with sku: 0
GET {{testEndpoint}}/shoes/0
### List all shoes with "retro" in the trim property
@trim = retro
GET {{testEndpoint}}/shoes?trim={{trim}}
### Save a new shoe
POST {{testEndpoint}}/shoes HTTP/1.1
Host: localhost:3000
Content-Type: application/json
User-Agent: PostmanRuntime/7.13.0
Accept: */*
Cache-Control: no-cache
Postman-Token: b7912595-d650-45d9-b993-6fc801ce27bd,0d1c1805-684f-4339-bab1-d41e30e717ab
Host: localhost:3000
accept-encoding: gzip, deflate
content-length: 93
Connection: keep-alive
cache-control: no-cache

{
    "year":"2019",
    "make":"Adidas",
    "model":"Predator",
    "trim":"King XL"
}

### 201x inventory
GET {{testEndpoint}}/inventory
### 201x inventory
GET {{testEndpoint}}/inventory?shoe.year=201
